In [2]:
import h5py
import numpy as np
import matplotlib.pyplot as plt
import yt

In [3]:
## Getting the file
filename = "/mnt/gs21/scratch/freem386/new_pgen_magpinch/MPsimple.out2.00000.athdf"
with h5py.File(filename, 'r') as f:
    print("Keys: %s" % f.keys())
    B = f['B'][:]
    prim = f['prim'][:]
    Levels = f['Levels'][:]
    LogicalLocations = f['LogicalLocations'][:]
    x1f = f['x1f'][:]
    x1v = f['x1v'][:]
    x2v = f['x2v'][:]

Keys: <KeysViewHDF5 ['B', 'Levels', 'LogicalLocations', 'prim', 'x1f', 'x1v', 'x2f', 'x2v', 'x3f', 'x3v']>


In [28]:
# plt.imshow(prim[2,:,:,:,:])
print(prim[0,:,0,:,:])

[[[0.00047975 0.00047741 0.00047506 ... 0.00046805 0.00046571 0.00046338]
  [0.00047975 0.00047741 0.00047506 ... 0.00046805 0.00046571 0.00046338]
  [0.00047975 0.00047741 0.00047506 ... 0.00046805 0.00046571 0.00046338]
  ...
  [0.00047975 0.00047741 0.00047506 ... 0.00046805 0.00046571 0.00046338]
  [0.00047975 0.00047741 0.00047506 ... 0.00046805 0.00046571 0.00046338]
  [0.00047975 0.00047741 0.00047506 ... 0.00046805 0.00046571 0.00046338]]

 [[0.00046105 0.00045872 0.0004564  ... 0.00044944 0.00044712 0.00044481]
  [0.00046105 0.00045872 0.0004564  ... 0.00044944 0.00044712 0.00044481]
  [0.00046105 0.00045872 0.0004564  ... 0.00044944 0.00044712 0.00044481]
  ...
  [0.00046105 0.00045872 0.0004564  ... 0.00044944 0.00044712 0.00044481]
  [0.00046105 0.00045872 0.0004564  ... 0.00044944 0.00044712 0.00044481]
  [0.00046105 0.00045872 0.0004564  ... 0.00044944 0.00044712 0.00044481]]

 [[0.00047975 0.00047741 0.00047506 ... 0.00046805 0.00046571 0.00046338]
  [0.00047975 0.000477

In [3]:
filename = "/mnt/gs21/scratch/freem386/new_pgen_magpinch/MPsimple.out2.00000.athdf"
ds = yt.load(filename)

yt : [WARNING  ] 2024-05-28 13:53:39,843 Assuming 1.0 = 1.0 cm
yt : [WARNING  ] 2024-05-28 13:53:39,844 Assuming 1.0 = 1.0 s
yt : [WARNING  ] 2024-05-28 13:53:39,845 Assuming 1.0 = 1.0 g
yt : [WARNING  ] 2024-05-28 13:53:39,846 Assuming 1.0 = 1.0 K
yt : [INFO     ] 2024-05-28 13:53:39,921 Parameters: current_time              = 0.0
yt : [INFO     ] 2024-05-28 13:53:39,923 Parameters: domain_dimensions         = [512 512   1]
yt : [INFO     ] 2024-05-28 13:53:39,924 Parameters: domain_left_edge          = [-3. -3. -1.]
yt : [INFO     ] 2024-05-28 13:53:39,925 Parameters: domain_right_edge         = [3. 3. 1.]
yt : [INFO     ] 2024-05-28 13:53:39,925 Parameters: cosmological_simulation   = 0
